version: '3.8'

services:
  web: 
    image: "node:18.3.0"
    working_dir: /app/web
    command: bash -c "npm i && npm run dev"
    volumes:
      - "./web:/app/web"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    expose: ["3000"]
    ports: ["3000:3000"]
